[package]
name = "rqrr"
edition = "2018"
version = "0.5.2"
authors = ["WanzenBug <moritz@wanzenbug.xyz>"]
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rqrr/"
repository = "https://github.com/WanzenBug/rqrr"
readme = "./README.md"
keywords = ["qrcode", "detection"]
description = """
Detect and read QR codes from any image source
"""
categories = [
    "graphics",
    "encoding",
]


[features]
img = ["image"]
default = ["img"]

[[bench]]
name = "bench_cap_find"
path = "benches/bench_cap_find.rs"
required-features = ["img"]
harness = false

[dev-dependencies]
criterion = "0.3"

[dependencies]
g2p = "0.4"
lru = "0.7.2"
image = { version = "0.24.0", optional = true }
